export const MAPS_API_KEY_NAME = 'NEXT_PUBLIC_MAPS_API_KEY';
export const FORMS_API_KEY_NAME = 'NEXT_PUBLIC_FORMS_KEY';
export const RECAPTCHA_SITE_KEY_NAME = 'NEXT_PUBLIC_RECAPTCHA_SITE_KEY';
export const TURNSTILE_SITE_KEY_NAME = 'NEXT_PUBLIC_TURNSTILE_SITE_KEY';
